usd:
  name: United States Dollar
  priority: 1
  iso_code: USD
  iso_numeric: "840"
  html_code: "&dollar;"
  symbol: "$"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 1
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
cny:
  name: Chinese Renminbi Yuan
  priority: 2
  iso_code: CNY
  iso_numeric: "156"
  html_code: "￥"
  symbol: "¥"
  minor_unit: Fen
  minor_unit_conversion: 100
  smallest_denomination: 1
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
hkd:
  name: Hong Kong Dollar
  priority: 3
  iso_code: HKD
  iso_numeric: "344"
  html_code: "$"
  symbol: "$"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 10
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
aud:
  name: Australian Dollar
  priority: 4
  iso_code: AUD
  iso_numeric: "036"
  html_code: "$"
  symbol: "$"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 5
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
eur:
  name: Euro
  priority: 5
  iso_code: EUR
  iso_numeric: "978"
  html_code: "&euro;"
  symbol: "€"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 1
  separator: ","
  delimiter: "."
  default_format: "%u%n"
  default_precision: 2
jpy:
  name: Japanese Yen
  priority: 6
  iso_code: JPY
  iso_numeric: "392"
  html_code: "&yen;"
  symbol: "¥"
  minor_unit:
  minor_unit_conversion: 1
  smallest_denomination: 1
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 0
gbp:
  name: British Pound
  priority: 7
  iso_code: GBP
  iso_numeric: "826"
  html_code: "&pound;"
  symbol: "£"
  minor_unit: Penny
  minor_unit_conversion: 100
  smallest_denomination: 1
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
cad:
  name: Canadian Dollar
  priority: 8
  iso_code: CAD
  iso_numeric: "124"
  html_code: "$"
  symbol: "$"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 5
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
sgd:
  name: Singapore Dollar
  priority: 9
  iso_code: SGD
  iso_numeric: "702"
  html_code: "$"
  symbol: "$"
  minor_unit: Cent
  minor_unit_conversion: 100
  smallest_denomination: 1
  separator: "."
  delimiter: ","
  default_format: "%u%n"
  default_precision: 2
