# Built-in conservative fallback exchange rates used when provider returns a sentinel
# value (e.g. 1) and caller did not supply an explicit fallback_rate.
# Keep this table small and conservative. Values are approximate recent averages.

CNY:
  USD: 0.14
  AUD: 0.21
  HKD: 1.09
USD:
  CNY: 7.17
  AUD: 1.56
  HKD: 7.81
AUD:
  CNY: 4.65
  USD: 0.64
HKD:
  CNY: 0.92
  USD: 0.13